baseURL = 'https://plabordab.github.io/portfolio_hugo'
languageCode = 'en-us'
title = 'Pilar Laborda'
theme = ['relearn']

defaultContentLanguage="es"

[params]
  themeVariant = "dwes"

[Languages]
    [Languages.es]
        title = "Ejemplo para el uso de idiomas"
        weight = 1
        languageName = "Español"

        contentDir = "content/es"

        [[Languages.es.menu.shortcuts]]
          name="<i class='fab fa-wikipedia-w'></i>   Wiki del curso"
          url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
          weight=1

        [[Languages.es.menu.shortcuts]]
          name="<i class='fad fa-book-reader'></i>   Apuntes Hugo"
          url="http://manuel.infenlaces.com/dwes/hugo/docs/teoria/"
          weight=2

        [[Languages.es.menu.shortcuts]]
          name="<i class='far fa-question-circle'></i>   Ejercicios resueltos"
          url="http://manuel.infenlaces.com/dwes/ejercicios/"
          weight=3

        [[Languages.es.menu.shortcuts]]
          name="<i class='fab fa-github'></i>   Repositorio"
          url="https://github.com/plabordab/ej_hugo"
          weight=4

    [Languages.en]
        title = "Example use language"
        weight = 2
        languageName = "English"

        contentDir = "content/en"

          [[Languages.en.menu.shortcuts]]
          name="<i class='fab fa-wikipedia-w'></i>   Course Wiki"
          url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
          weight=1

        [[Languages.en.menu.shortcuts]]
          name="<i class='fad fa-book-reader'></i>   Hugo notes"
          url="http://manuel.infenlaces.com/dwes/hugo/docs/teoria/"
          weight=2

        [[Languages.en.menu.shortcuts]]
          name="<i class='far fa-question-circle'></i>   Solved exercises"
          url="http://manuel.infenlaces.com/dwes/ejercicios/"
          weight=3

        [[Languages.en.menu.shortcuts]]
          name="<i class='fab fa-github'></i>   Repository"
          url="https://github.com/plabordab/ej_hugo"
          weight=4

   [Languages.fr]
        title = "Exemple d'utilisation des langues"
        weight = 3
        languageName = "Français"

        contentDir = "content/fr"

          [[Languages.fr.menu.shortcuts]]
          name="<i class='fab fa-wikipedia-w'></i>   Cours Wiki"
          url="https://es.wikieducator.org/Usuario:ManuelRomero/ProgramacionWeb/Contenido"
          weight=1

        [[Languages.fr.menu.shortcuts]]
          name="<i class='fad fa-book-reader'></i>   Notes Hugo"
          url="http://manuel.infenlaces.com/dwes/hugo/docs/teoria/"
          weight=2

        [[Languages.fr.menu.shortcuts]]
          name="<i class='far fa-question-circle'></i>   Exercices résolus"
          url="http://manuel.infenlaces.com/dwes/ejercicios/"
          weight=3

        [[Languages.fr.menu.shortcuts]]
          name="<i class='fab fa-github'></i>   Référentiel"
          url="https://github.com/plabordab/ej_hugo"
          weight=4