baseURL = 'https://plabordab.github.io/portfolio_hugo'
languageCode = 'en-us'
title = 'Pilar Laborda'
theme = ['relearn']

defaultContentLanguage="es"

[params]
  themeVariant = "dwes"

# Gráficos

[params.mermaid]
    enable = true


# Idiomas

[Languages]
    [Languages.es]
        weight = 1
        languageName = "Español"

        contentDir = "content/es"

        [[Languages.es.menu.shortcuts]]
          name="<i class='fab fa-2x fa-linkedin'></i>   Linkedin"
         url = "https://www.linkedin.com/in/pilar-laborda-berd%C3%BAn-13568060"
          weight=1

        [[Languages.es.menu.shortcuts]]
          name="<i class='fab fa-2x fa-github'></i>   Repositorio"
          url="https://github.com/plabordab"
          weight=2

        [[Languages.es.menu.shortcuts]]
          name="<i class='fas fa-2x fa-envelope'></i>   Email"
          url = "mailto:pilarlabordaweb@gmail.com"
          weight=3



    [Languages.en]
        weight = 2
        languageName = "English"

        contentDir = "content/en"

          [[Languages.en.menu.shortcuts]]
          name="<i class='fab fa-2x fa-linkedin'></i>   Linkedin"
          url = "https://www.linkedin.com/in/pilar-laborda-berd%C3%BAn-13568060"
          weight=1

        [[Languages.en.menu.shortcuts]]
          name="<i class='fab fa-2x fa-github'></i>   Repository"
          url="https://github.com/plabordab"
          weight=2

        [[Languages.en.menu.shortcuts]]
          name="<i class='fas fa-2x fa-envelope'></i>   Email"
          url = "mailto:pilarlabordaweb@gmail.com"
          weight=3


   [Languages.fr]
        weight = 3
        languageName = "Français"

        contentDir = "content/fr"

          [[Languages.fr.menu.shortcuts]]
          name="<i class='fab fa-2x fa-linkedin'></i>   Linkedin"
          url = "https://www.linkedin.com/in/pilar-laborda-berd%C3%BAn-13568060"
          weight=1

        [[Languages.fr.menu.shortcuts]]
          name="<i class='fab fa-2x fa-github'></i>   Référentiel"
          url="https://github.com/plabordab"
          weight=2

        [[Languages.fr.menu.shortcuts]]
          name="<i class='fas fa-2x fa-envelope'></i>   Email"
          url = "mailto:pilarlabordaweb@gmail.com"
          weight=3
